### ISSUE TITLE
How to use this set of repositories?

### ISSUE THREAD

**Issue by ArsenShnurkov** [textcreationpartnership/Texts#1]
I want to read the book

<code>
"A18267","23586843","26742","STC 4884.5; ESTC S4581","Restricted","Cawdry, Robert.; T. C.","1609",
"A table alphabeticall contayning and teaching the true writing and vnderstanding of hard vsuall English wordes, borrowed from the Hebrew, Greeke, Latine, or French &c. :
with the interpretation thereof by plaine English words, gathered for the benefit and help of all vnskilfull persons :
whereby they may the more easily and better vnderstand many hard English words, which they shall heare or read in Scriptures,
sermons, or elsewhere, and also be made able to vse the same aptly themselues / set foorth by R.C. ; and newly corrected, and much inlarged by T.C.",
"English language -- Dictionaries -- Early works to 1700.", 150
</code>

but there is neither repository at url https://github.com/textcreationpartnership/A18267 nor the wget command in  graball.sh ...

**Comment by sebastianrahtz** [comment]
That text is restricted, in other words it can't be released for another 5 years, except to members of the EEBO consortium. If your institution is a member of the consortium, let me know.
Sebastian Rahtz

Carved in stone on my iPad
